
#if 0
struct run_segment {
  enum {
    WarmingUp,
    WalkingPace,
    RunningPace,
    FastPace,
    CoolingDown,
  } category;
  uint32_t duration;
};

struct run {
  std::string name;
  std::vector<run_segment> segments;
};

struct program {
  std::vector<run> runs;
};

program hiit {{
  run{ "hiit_5k", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 290},
    run_segment{FastPace, 10},
    run_segment{RunningPace, 50},
    run_segment{FastPace, 10},
  }}
}};

program c25k = {{
  run{ "W1D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{CoolingDown, 300},
  }},
  run{ "W1D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{CoolingDown, 300},
  }},
  run{ "W1D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 60},
    run_segment{CoolingDown, 300},
  }},
  run{ "W2D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{CoolingDown, 300},
  }},
  run{ "W2D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{CoolingDown, 300},
  }},
  run{ "W2D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 150},
    run_segment{RunningPace, 90},
    run_segment{CoolingDown, 300},
  }},
  run{ "W3D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 180},
    run_segment{CoolingDown, 300},
  }},
  run{ "W3D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 180},
    run_segment{CoolingDown, 300},
  }},
  run{ "W3D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 90},
    run_segment{WalkingPace, 90},
    run_segment{RunningPace, 180},
    run_segment{CoolingDown, 300},
  }},
  run{ "W4D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{WalkingPace, 300},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{CoolingDown, 300},
  }},
  run{ "W4D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{WalkingPace, 300},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{CoolingDown, 300},
  }},
  run{ "W4D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{WalkingPace, 300},
    run_segment{RunningPace, 180},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{CoolingDown, 300},
  }},
  run{ "W5D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 300},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{CoolingDown, 300},
  }},
  run{ "W5D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 480},
    run_segment{WalkingPace, 300},
    run_segment{RunningPace, 480},
    run_segment{CoolingDown, 300},
  }},
  run{ "W5D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1200},
    run_segment{CoolingDown, 300},
  }},
  run{ "W6D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 300},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 480},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 300},
    run_segment{CoolingDown, 300},
  }},
  run{ "W6D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 600},
    run_segment{WalkingPace, 180},
    run_segment{RunningPace, 600},
    run_segment{CoolingDown, 300},
  }},
  run{ "W6D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1320},
    run_segment{CoolingDown, 300},
  }},
  run{ "W7D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1500},
    run_segment{CoolingDown, 300},
  }},
  run{ "W7D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1500},
    run_segment{CoolingDown, 300},
  }},
  run{ "W7D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1500},
    run_segment{CoolingDown, 300},
  }},
  run{ "W8D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1680},
    run_segment{CoolingDown, 300},
  }},
  run{ "W8D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1680},
    run_segment{CoolingDown, 300},
  }},
  run{ "W8D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1680},
    run_segment{CoolingDown, 300},
  }},
  run{ "W9D1", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1800},
    run_segment{CoolingDown, 300},
  }},
  run{ "W9D2", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1800},
    run_segment{CoolingDown, 300},
  }},
  run{ "W9D3", {
    run_segment{WarmingUp, 300},
    run_segment{RunningPace, 1800},
    run_segment{CoolingDown, 300},
  }},
}};

#endif
